namespace AngelScript;

[Flags]
public enum ObjectTypeFlags : ulong {
    Ref = asEObjTypeFlags.asOBJ_REF,
    Value = asEObjTypeFlags.asOBJ_VALUE,
    GC = asEObjTypeFlags.asOBJ_GC,
    Pod = asEObjTypeFlags.asOBJ_POD,
    NoHandle = asEObjTypeFlags.asOBJ_NOHANDLE,
    Scoped = asEObjTypeFlags.asOBJ_SCOPED,
    Template = asEObjTypeFlags.asOBJ_TEMPLATE,
    AsHandle = asEObjTypeFlags.asOBJ_ASHANDLE,
    AppClass = asEObjTypeFlags.asOBJ_APP_CLASS,
    AppClassConstructor = asEObjTypeFlags.asOBJ_APP_CLASS_CONSTRUCTOR,
    AppClassDestructor = asEObjTypeFlags.asOBJ_APP_CLASS_DESTRUCTOR,
    AppClassAssignment = asEObjTypeFlags.asOBJ_APP_CLASS_ASSIGNMENT,
    AppClassCopyContructor = asEObjTypeFlags.asOBJ_APP_CLASS_COPY_CONSTRUCTOR,
    AppClassC = asEObjTypeFlags.asOBJ_APP_CLASS_C,
    AppClassCD = asEObjTypeFlags.asOBJ_APP_CLASS_CD,
    AppClassCA = asEObjTypeFlags.asOBJ_APP_CLASS_CA,
    AppClassCK = asEObjTypeFlags.asOBJ_APP_CLASS_CK,
    AppClassCDA = asEObjTypeFlags.asOBJ_APP_CLASS_CDA,
    AppClassCDK = asEObjTypeFlags.asOBJ_APP_CLASS_CDK,
    AppClassCAK = asEObjTypeFlags.asOBJ_APP_CLASS_CAK,
    AppClassCDAK = asEObjTypeFlags.asOBJ_APP_CLASS_CDAK,
    AppClassD = asEObjTypeFlags.asOBJ_APP_CLASS_D,
    AppClassDA = asEObjTypeFlags.asOBJ_APP_CLASS_DA,
    AppClassDK = asEObjTypeFlags.asOBJ_APP_CLASS_DK,
    AppClassDAK = asEObjTypeFlags.asOBJ_APP_CLASS_DAK,
    AppClassA = asEObjTypeFlags.asOBJ_APP_CLASS_A,
    AppClassAK = asEObjTypeFlags.asOBJ_APP_CLASS_AK,
    AppClassK = asEObjTypeFlags.asOBJ_APP_CLASS_K,
    AppClassMoreConstructors = asEObjTypeFlags.asOBJ_APP_CLASS_MORE_CONSTRUCTORS,
    AppPrimitive = asEObjTypeFlags.asOBJ_APP_PRIMITIVE,
    AppFloat = asEObjTypeFlags.asOBJ_APP_FLOAT,
    AppArray = asEObjTypeFlags.asOBJ_APP_ARRAY,
    AppClassAllInts = asEObjTypeFlags.asOBJ_APP_CLASS_ALLINTS,
    AppClassAllFloats = asEObjTypeFlags.asOBJ_APP_CLASS_ALLFLOATS,
    NoCount = asEObjTypeFlags.asOBJ_NOCOUNT,
    AppClassAlign8 = asEObjTypeFlags.asOBJ_APP_CLASS_ALIGN8,
    ImplicitHandle = asEObjTypeFlags.asOBJ_IMPLICIT_HANDLE,
    AppClassUnion = asEObjTypeFlags.asOBJ_APP_CLASS_UNION,
    MaskValidFlags = asEObjTypeFlags.asOBJ_MASK_VALID_FLAGS,
    ScriptObject = asEObjTypeFlags.asOBJ_SCRIPT_OBJECT,
    Shared = asEObjTypeFlags.asOBJ_SHARED,
    NoInherit = asEObjTypeFlags.asOBJ_NOINHERIT,
    FuncDef = asEObjTypeFlags.asOBJ_FUNCDEF,
    ListPattern = asEObjTypeFlags.asOBJ_LIST_PATTERN,
    Enum = asEObjTypeFlags.asOBJ_ENUM,
    TemplateSubtype = asEObjTypeFlags.asOBJ_TEMPLATE_SUBTYPE,
    TypeDef = asEObjTypeFlags.asOBJ_TYPEDEF,
    Abstract = asEObjTypeFlags.asOBJ_ABSTRACT,
    AppAlign16 = asEObjTypeFlags.asOBJ_APP_ALIGN16,
}